### ISSUE TITLE
execise.ipynbs need Lightning in colab

### ISSUE THREAD

**Issue by matthiasdellago** [callummcdougall/ARENA_2.0#20]
In exercises 1.1 and 1.2 (and probably more) running in colab results in :
`ModuleNotFoundError: No module named 'pytorch_lightning'

This can be fixed by including:

if IN_COLAB:
    # Install packages
    %pip install pytorch-lightning
    
I could't find the exercise.ipynb files in the repo, if you can point me towards them I'll also gladly submit a PR.

P.S.: Thanks for providing this awesome content! :)

**Comment by callummcdougall** [comment]
No problem, glad you're enjoying it!

If this is referring to the first 2 exercise sets in the transformers material, I think they should both be fixed now? There shouldn't be any notebooks in the repo (I develop the exercises in notebooks but these are ignored in the "gitignore" file; they're just for development rather than for use). Let me know if there are still any issues though!

**Comment by matthiasdellago** [comment]
Ah, I should have specified:
I'm talking about [this notebook](https://colab.research.google.com/drive/1w9zCWpE7xd1sDuMT_rsjARfFozeWiKF4#scrollTo=5g0vLQbLdbSQ)  linked from [this streamlit page](https://arena-ch1-transformers.streamlit.app/[1.2]_Intro_to_Mech_Interp) . I think the other notebooks have the same problem.

**Comment by callummcdougall** [comment]
Ah, I see the issue - I'd removed the lightning install from the colabs, but hadn't quite removed it from all of the files in the repo. Have done so now, everything seems to be working. Thanks!
